export const SITE_CONFIG = {
  name: "Royal Phuket City Hotel",
  tagline: "Heritage Hospitality at Its Finest",
  description:
    "Experience luxury and comfort at Royal Phuket City Hotel, a 4-star hotel in the heart of Phuket Old Town. 251 elegant rooms, 5 dining venues, and world-class facilities.",
  url: "https://royalphuketcity.com",
  ogImage: "/images/og-image.jpg",
} as const;

export const HOTEL_INFO = {
  name: "Royal Phuket City Hotel",
  starRating: 4,
  address: "154 Phang-Nga Road, Talad Yai, Muang, Phuket 83000, Thailand",
  phone: "+66 76 233 355",
  email: "reservation@royalphuketcity.com",
  checkIn: "2:00 PM",
  checkOut: "12:00 PM",
  totalRooms: 251,
  totalRestaurants: 5,
  meetingRooms: 9,
  parkingSpaces: 350,
  building: "19-story (first high-rise in Phuket, tallest near Old Town)",
  architecture: "Contemporary Classic",
} as const;

export const EXTERNAL_LINKS = {
  booking: "https://www.myxcaliber.com/ibe/b/Royal-Phuket-City-Hotel",
  facebook: "https://www.facebook.com/royalphuketcity/",
  instagram: "https://www.instagram.com/royalphuketcity/",
  tripadvisor:
    "https://www.tripadvisor.com/Hotel_Review-g1215781-d309104-Reviews-Royal_Phuket_City_Hotel-Phuket_Town_Phuket.html",
  googleMaps:
    "https://maps.app.goo.gl/3Q65GyZvmkpR9DfGA",
} as const;

export const NAV_LINKS = {
  left: [
    { label: "Home", href: "/" },
    {
      label: "Rooms & Suites",
      href: "/rooms-suites",
      dropdown: [
        { label: "All Rooms & Suites", href: "/rooms-suites" },
        { label: "Premier Superior", href: "/rooms-suites/premier-superior" },
        { label: "Premier Superior Partial Sea View", href: "/rooms-suites/premier-superior-partial-sea-view" },
        { label: "Premier Deluxe", href: "/rooms-suites/premier-deluxe" },
        { label: "Premier Deluxe Partial Sea View", href: "/rooms-suites/premier-deluxe-partial-sea-view" },
        { label: "Suite Room", href: "/rooms-suites/suite-room" },
        { label: "Executive Suite", href: "/rooms-suites/executive-suite" },
      ],
    },
    { label: "Promotions", href: "/promotions" },
    { label: "Facilities", href: "/facilities" },
    {
      label: "Wedding",
      href: "/wedding-venues",
      dropdown: [
        { label: "Wedding Venues", href: "/wedding-venues" },
        { label: "Engagement Ceremony", href: "/wedding-venues/engagement-ceremony" },
        { label: "Thai Wedding", href: "/wedding-venues/thai-wedding" },
        { label: "Chinese Wedding", href: "/wedding-venues/chinese-wedding" },
        { label: "Muslim Wedding", href: "/wedding-venues/muslim-wedding" },
        { label: "Western Wedding", href: "/wedding-venues/western-wedding" },
        { label: "LGBTQ+ Wedding", href: "/wedding-venues/lgbtq-wedding" },
      ],
    },
  ],
  right: [
    {
      label: "Meeting & Events",
      href: "/meeting-events",
      dropdown: [
        { label: "All Venues & Events", href: "/meeting-events" },
        { label: "Corporate Conference", href: "/meeting-events/corporate-conference" },
        { label: "Seminar & Workshop", href: "/meeting-events/seminar-workshop" },
        { label: "Product Launch", href: "/meeting-events/product-launch" },
        { label: "Gala Dinner & Awards", href: "/meeting-events/gala-dinner-award" },
        { label: "Exhibition & Trade Show", href: "/meeting-events/exhibition-trade-show" },
        { label: "Concert & Live Show", href: "/meeting-events/concert-live-performance" },
        { label: "Stand-Up Comedy", href: "/meeting-events/stand-up-comedy" },
        { label: "Talk Show & Panel", href: "/meeting-events/talk-show-panel" },
        { label: "Graduation Ceremony", href: "/meeting-events/graduation-ceremony" },
        { label: "Download Fact Sheets", href: "/download-fact-sheets" },
      ],
    },
    {
      label: "Dining",
      href: "/dining",
      dropdown: [
        {
          label: "Yan Long Chinese Restaurant",
          href: "/yan-long-chinese-restaurant",
        },
        {
          label: "TWIST Rooftop Restaurant & Bar",
          href: "/twist-rooftop-restaurant-bar",
        },
        { label: "Good Eatz 154", href: "/good-eatz-154" },
      ],
    },
    {
      label: "About",
      href: "#",
      dropdown: [
        { label: "Artist", href: "/artist" },
        { label: "Royal Green", href: "/royal-green" },
        { label: "Sustainability", href: "/sustainability" },
      ],
    },
    { label: "Contact", href: "/contact" },
  ],
} as const;

export const ROOMS = [
  {
    slug: "premier-superior",
    name: "Premier Superior",
    category: "Premier",
    size: "30 sqm",
    maxGuests: 2,
    bedType: "Twin",
    views: ["City View"],
    shortDescription:
      "The perfect space and place for relaxing with city view and full amenities.",
    image: "/images/rooms/01 Premier superior/Premier Superior 1.jpg",
  },
  {
    slug: "premier-superior-partial-sea-view",
    name: "Premier Superior - Partial Sea View",
    category: "Premier",
    size: "30 sqm",
    maxGuests: 2,
    bedType: "King or Twin",
    views: ["Partial Sea View"],
    shortDescription:
      "Wake up to glimpses of the Andaman Sea from your elegantly appointed Premier Superior room.",
    image: "/images/rooms/02 Premier superior - Partial sea view/Premier Superior 1.jpg",
  },
  {
    slug: "premier-deluxe",
    name: "Premier Deluxe",
    category: "Premier",
    size: "38 sqm",
    maxGuests: 2,
    bedType: "King or Twin",
    views: ["City View"],
    shortDescription:
      "An ideal option for business travelers with everything you expect from a 4-star hotel.",
    image: "/images/rooms/03 Premier deluxe/Premier Deluxe 1.jpg",
  },
  {
    slug: "premier-deluxe-partial-sea-view",
    name: "Premier Deluxe - Partial Sea View",
    category: "Premier",
    size: "38 sqm",
    maxGuests: 2,
    bedType: "King or Twin",
    views: ["Partial Sea View"],
    shortDescription:
      "Elevated comfort with partial sea views and premium furnishings in 38 m² of luxury.",
    image: "/images/rooms/04 Premier deluxe - Partial sea view/Premier deluxe - Partial sea view01_resize.jpg",
  },
  {
    slug: "suite-room",
    name: "Suite Room",
    category: "Suite",
    size: "64 sqm",
    maxGuests: 2,
    bedType: "King",
    views: ["Panoramic City View"],
    shortDescription:
      "Featuring an impressive living room, comfortable bathroom, and free Wi-Fi in 64 m² of luxury.",
    image: "/images/rooms/05 Suite/Suite01_resize.jpg",
  },
  {
    slug: "executive-suite",
    name: "Executive Suite Room",
    category: "Executive",
    size: "75 sqm",
    maxGuests: 2,
    bedType: "King",
    views: ["Panoramic Sea & City View"],
    shortDescription:
      "A luxurious living room, comfortable bathroom with bathtub, and free Wi-Fi in 75 m² of ultimate luxury.",
    image: "/images/rooms/06 Executive suite/Executive Suites 7.jpg",
  },
] as const;

export const RESTAURANTS = [
  {
    slug: "yan-long-chinese-restaurant",
    name: "Yan Long Chinese Restaurant",
    cuisine: "Chinese",
    floor: "Ground Floor",
    hours: "11:00 AM – 10:00 PM",
    shortDescription:
      "Authentic Cantonese cuisine with dim sum specialties and private dining rooms.",
    image: "/images/HOTEL WEBSITE/Restaurant/YanLong_L01_full_dining_room_L.jpg",
  },
  {
    slug: "twist-rooftop-restaurant-bar",
    name: "TWIST Rooftop Restaurant & Bar",
    cuisine: "International",
    floor: "19th Floor",
    hours: "5:00 PM – 12:00 AM",
    shortDescription:
      "Rooftop dining with panoramic views, craft cocktails, and international cuisine.",
    image: "/images/HOTEL WEBSITE/Restaurant/Twist ROoftop.jpg",
  },
  {
    slug: "good-eatz-154",
    name: "Good Eatz 154",
    cuisine: "Thai & International",
    floor: "Ground Floor",
    hours: "6:00 AM – 10:00 PM",
    shortDescription:
      "All-day dining featuring Thai favorites and international breakfast buffet.",
    image: "/images/HOTEL WEBSITE/Restaurant/RPC_LM06_mixed_tourists_goodeatz_lunch_L.jpg",
  },
] as const;

export const FACILITIES = [
  {
    name: "Rooftop Breakfast",
    description: "Start your day with breathtaking views from the 19th floor.",
    image: "/images/HOTEL WEBSITE/Restaurant/TWIST Rooftop 005.jpg",
  },
  {
    name: "Swimming Pool",
    description: "Outdoor pool with sun loungers and poolside service.",
    image: "/images/HOTEL WEBSITE/RPC Pool 01.jpeg",
  },
  {
    name: "Fitness Center",
    description: "State-of-the-art equipment available 24 hours.",
    image: "/images/HOTEL WEBSITE/Royal-Phuket-City-Fitness_07.jpg",
  },
  {
    name: "Spa & Massage",
    description: "Rejuvenating treatments inspired by Thai wellness traditions.",
    image: "/images/HOTEL WEBSITE/Royal-Wellness-Spa-7.jpg",
  },
  {
    name: "Atrium Lounge",
    description: "Elegant space for afternoon tea and light refreshments.",
    image: "/images/HOTEL WEBSITE/Atrium-Lounge-Royal-Phuket-City-Hotel-1.jpg",
  },
  {
    name: "Smart Bus",
    description: "Complimentary shuttle service to popular destinations.",
    image: "/images/HOTEL WEBSITE/Smart-Bus.jpeg",
  },
  {
    name: "EV Charger",
    description: "Electric vehicle charging stations for eco-conscious travelers.",
    image: "/images/HOTEL WEBSITE/EV-Bus_resize-1.jpeg",
  },
] as const;

export const PROMOTIONS = [
  {
    slug: "stay-2-pay-1",
    title: "The Stay 2 Pay 1 Offer",
    subtitle: "Two Nights, Pay for One",
    tagline: "Best Value",
    category: "Short Stay",
    validFrom: "2026-04-09",
    validUntil: "2026-09-30",
    image: "/images/HOTEL WEBSITE/RPC LS ROOM 27.jpg",
    shortDescription: "Experience the heart of Phuket Old Town with our Stay 2 Pay 1 special. By planning your trip just 7 days in advance, you receive a complimentary second night, making this our most efficient rate for a two-night city escape.",
    highlights: [
      "2 nights in a Premier Superior room",
      "Daily breakfast included for two guests",
      "Effective rate from ฿2,200 for 2 nights (Avg. ฿1,100/night)",
      "Minimum 7-day advance booking required",
      "10% off all restaurant dining and spa treatments",
    ],
    terms: [
      "Booking period: 9 April – 30 September 2026",
      "Stay period: 1 May – 10 January 2027",
      "Booking method: use code STAYON via hotel website",
      "Minimum 7-day advance booking required",
      "Subject to availability; cannot be combined with other promotions",
    ],
    price: "From ฿2,200 / 2 nights",
    originalPrice: "Avg. ฿1,100/night",
    bookingCode: "STAYON",
  },
  {
    slug: "family-nest",
    title: "Family Nest",
    subtitle: "Connecting Rooms for the Whole Crew",
    tagline: "Family Package",
    category: "Family",
    validFrom: "2026-06-20",
    validUntil: "2026-10-15",
    image: "/images/HOTEL WEBSITE/RPC LS ROOM 21.jpg",
    shortDescription: "Gather the whole crew for the ultimate family getaway in Phuket Old Town. Our Family Nest package offers the perfect balance of togetherness and privacy with guaranteed connecting rooms and daily breakfast for everyone.",
    highlights: [
      "Guaranteed 2 connecting rooms setup",
      "Daily breakfast for up to 4 guests",
      "Premier Superior: From ฿3,799 for 2 rooms",
      "Premier Deluxe: From ฿4,999 for 2 rooms",
      "Capacity: 4 Adults + 2 Extra Beds + 2 Children",
      "10% off all restaurant dining and spa treatments",
    ],
    terms: [
      "Booking period: 20 June – 15 October 2026",
      "Stay period: 20 June – 15 October 2026",
      "Subject to availability; recommended to book in advance",
      "Extra beds available upon request",
      "Cannot be combined with other promotions",
    ],
    price: "From ฿3,799 / 2 rooms",
    originalPrice: "",
    bookingCode: "",
  },
  {
    slug: "sun-and-fun",
    title: "Sun & Fun",
    subtitle: "Kids Stay & Eat Free",
    tagline: "Kids Free",
    category: "Family",
    validFrom: "2026-06-20",
    validUntil: "2026-10-15",
    image: "/images/HOTEL WEBSITE/RPC LS ROOM 38.jpg",
    shortDescription: "Make your next holiday a breeze with our Sun & Fun special, where kids stay and eat absolutely free. Tailored for small families, this package features rooms equipped with one double bed and one single bed.",
    highlights: [
      "Available across all room types (1 Double + 1 Single Bed)",
      "Daily breakfast included",
      "1 Child under 12 stays and eats FREE",
      "Premier Superior: ฿2,000/night",
      "Premier Superior Sea View: ฿2,300/night",
      "Premier Deluxe: ฿2,600/night | Sea View: ฿2,900/night",
      "10% off all restaurant dining and spa treatments",
    ],
    terms: [
      "Booking period: 20 June – 15 October 2026",
      "Stay period: 20 June – 15 October 2026",
      "Booking method: use code SUNFUN via hotel website",
      "Maximum 1 child under 12 per room",
      "Subject to availability; cannot be combined with other promotions",
    ],
    price: "From ฿2,000/night",
    originalPrice: "Kids Free",
    bookingCode: "SUNFUN",
  },
  {
    slug: "splash-and-stay",
    title: "Splash & Stay",
    subtitle: "Hotel + Andamanda Water Park",
    tagline: "Water Park Included",
    category: "Experience",
    validFrom: "2026-06-20",
    validUntil: "2026-10-15",
    image: "/images/HOTEL WEBSITE/RPC-Pool-Wall-scaled.jpg",
    shortDescription: "Dive into excitement with our all-in-one Splash & Stay bundle package. This premium offer pairs a relaxing two-night city escape with an adrenaline-pumping day at Phuket's premier Andamanda Water Park.",
    highlights: [
      "2 nights stay in your selected room",
      "Daily breakfast for two guests",
      "2 Andamanda Water Park Day Pass tickets",
      "Premier Superior: ฿5,200 | Sea View: ฿5,700",
      "Premier Deluxe: ฿6,200 | Sea View: ฿6,700",
      "10% off all restaurant dining and spa treatments",
    ],
    terms: [
      "Booking period: 20 June – 15 October 2026",
      "Stay period: 20 June – 15 October 2026",
      "Minimum 2-night stay required",
      "Water park tickets valid during stay period only",
      "Subject to availability; cannot be combined with other promotions",
    ],
    price: "From ฿5,200 / 2 nights",
    originalPrice: "Includes Water Park",
    bookingCode: "",
  },
  {
    slug: "family-getaway",
    title: "Happy Family Getaway",
    subtitle: "School Break Value Package",
    tagline: "April–May Special",
    category: "Family",
    validFrom: "2026-04-01",
    validUntil: "2026-05-31",
    image: "/images/promotions/RPC LS ROOM 21.jpg",
    shortDescription: "Perfect for Thai families during school break! Enjoy quality time together with spacious rooms, kids' activities, and family-friendly dining.",
    highlights: [
      "Spacious Premier Deluxe room for the family",
      "Daily breakfast for 2 adults + 2 kids",
      "Kids under 12 stay free",
      "Welcome gift for children",
      "Late checkout until 2:00 PM",
      "Access to swimming pool & fitness center",
    ],
    terms: [
      "Valid for stays April 1 – May 31, 2026",
      "Maximum 2 children under 12 per room",
      "Children must share existing bedding",
      "Minimum 2-night stay required",
      "Subject to availability",
    ],
    price: "From ฿1,800/night",
    originalPrice: "",
    bookingCode: "FAMILYBREAK",
  },
  {
    slug: "songkran-package",
    title: "Songkran @ RPC",
    subtitle: "Old Town Base Camp",
    tagline: "Songkran 2026",
    category: "Seasonal",
    validFrom: "2026-04-12",
    validUntil: "2026-04-16",
    image: "/images/promotions/RPC LS ROOM 38.jpg",
    shortDescription: "Celebrate Songkran in the heart of Phuket Old Town! Your perfect base camp for Thailand's biggest water festival with everything you need to join the fun.",
    highlights: [
      "Comfortable room accommodation",
      "Daily breakfast buffet",
      "Songkran Survival Kit included",
      "Waterproof phone pouch",
      "Quick-dry towel",
      "Old Town Songkran event map & tips",
    ],
    terms: [
      "Valid for stays April 12–16, 2026",
      "Minimum 2-night stay recommended",
      "One survival kit per room",
      "Subject to availability — book early",
      "Non-refundable during Songkran period",
    ],
    price: "From ฿2,499/night",
    originalPrice: "฿3,200/night",
    bookingCode: "SONGKRAN2026",
  },
  {
    slug: "april-residence-deal",
    title: "The April Residence Deal",
    subtitle: "Exclusive for Thai Nationals & Residents",
    tagline: "Thai Residents Only",
    category: "Thai Residents",
    validFrom: "2026-04-09",
    validUntil: "2026-04-30",
    image: "/images/HOTEL WEBSITE/RPC LS ROOM 11.jpg",
    shortDescription: "Take advantage of our exclusive April Residence Deal, specifically curated for Thai nationals and residents. Experience the historic charm of Phuket Old Town with enterprise-grade hospitality and premium seasonal perks at an unbeatable rate.",
    highlights: [
      "Special rate from ฿1,699 / night",
      "Rooftop breakfast buffet at our signature dining venue",
      "฿300 daily dining credit at hotel outlets",
      "Complimentary upgrade to Partial Sea View (subject to availability)",
      "10% off all restaurant dining and spa treatments",
      "Exclusive access for Thai nationals and work permit holders",
    ],
    terms: [
      "Booking period: 9 – 30 April 2026",
      "Stay period: 9 – 21 April and 27 – 30 April 2026",
      "Booking method: use code APR26 via hotel website or direct call",
      "Verification: valid Thai ID or Work Permit must be presented at check-in",
      "Limited rooms available; offer cannot be combined with other promotions",
    ],
    price: "From ฿1,699/night",
    originalPrice: "",
    bookingCode: "APR26",
  },
  {
    slug: "blissful-3-night",
    title: "The Blissful 3-Night Package",
    subtitle: "Stay 3, Get Spa & Rooftop Dining",
    tagline: "Spa & Dining Included",
    category: "Wellness Package",
    validFrom: "2026-04-09",
    validUntil: "2026-06-30",
    image: "/images/HOTEL WEBSITE/RPC LS ROOM 47.jpg",
    shortDescription: "The Stay 3 Get More package is designed for guests seeking a complete retreat. This bundle integrates premium hospitality services — including professional spa therapy and curated dining — into a single, value-indexed rate of ฿5,397.",
    highlights: [
      "3 nights in a Premier Superior room",
      "Daily breakfast for two guests",
      "One 60-minute spa treatment for two guests",
      "One inclusive dinner at TWIST Rooftop for two guests",
      "Total package value ฿5,397 net",
      "10% off all restaurant dining and spa treatments",
    ],
    terms: [
      "Booking period: 9 April – 30 June 2026",
      "Stay period: 1 May – 30 June 2026",
      "Booking method: use code BLISS3 via hotel website",
      "Spa treatment must be reserved in advance",
      "Subject to availability; cannot be combined with other promotions",
    ],
    price: "฿5,397 / 3 nights",
    originalPrice: "Net package rate",
    bookingCode: "BLISS3",
  },
  {
    slug: "weekly-stay-7",
    title: "The 7-Day Weekly Stay",
    subtitle: "Workation-Ready Weekly Rate",
    tagline: "Weekly Rate",
    category: "Extended Stay",
    validFrom: "2026-04-09",
    validUntil: "2026-06-30",
    image: "/images/HOTEL WEBSITE/RPC LS ROOM 33.jpg",
    shortDescription: "Designed for extended exploration or a seamless workation, our Weekly Stay rate offers a fixed 7-night price of ฿10,493. This package provides the necessary infrastructure for longer visits, including laundry services and multiple dinner credits.",
    highlights: [
      "7 nights in a Premier Superior room",
      "Daily breakfast for two guests",
      "Two inclusive dinners at TWIST Rooftop for two guests",
      "4 pieces of laundry included per stay",
      "Total weekly rate ฿10,493 net",
      "10% off all restaurant dining and spa treatments",
    ],
    terms: [
      "Booking period: 9 April – 30 June 2026",
      "Stay period: 1 May – 30 June 2026",
      "Booking method: use code LIVEIN via hotel website",
      "Laundry credit non-transferable and not refundable for cash",
      "Subject to availability; cannot be combined with other promotions",
    ],
    price: "฿10,493 / 7 nights",
    originalPrice: "Net weekly rate",
    bookingCode: "LIVEIN",
  },
] as const;
