export interface MiceEventTypeDetail {
  slug: string;
  title: string;
  subtitle: string;
  label: string;
  heroImage: string;
  description: string[];
  features: {
    title: string;
    description: string;
  }[];
  whyChooseUs: string[];
  idealFor: string[];
  venueOptions: {
    name: string;
    capacity: string;
    bestFor: string;
  }[];
  gallery: string[];
  seoKeywords: string[];
  metaDescription: string;
}

export const MICE_EVENT_TYPES: Record<string, MiceEventTypeDetail> = {
  "corporate-conference": {
    slug: "corporate-conference",
    title: "Corporate Conference",
    subtitle: "Professional Spaces for Impactful Business Gatherings",
    label: "Corporate Excellence",
    heroImage: "/images/HOTEL WEBSITE/EVT_TS_L01_panel_stage_wide.jpg",
    metaDescription: "Host your corporate conference in Phuket at Royal Phuket City Hotel. Professional venues accommodating up to 2,300 guests with state-of-the-art AV equipment, dedicated event teams, and 27+ years of MICE experience.",
    seoKeywords: ["corporate conference Phuket", "business conference venue Thailand", "conference hotel Phuket", "corporate meeting venue Phuket", "MICE conference Phuket", "annual conference venue Thailand", "corporate event space Phuket"],
    description: [
      "Royal Phuket City Hotel stands as Southern Thailand's premier destination for corporate conferences, offering an unmatched combination of professional facilities, experienced staff, and strategic location. With over 27 years of hosting successful business events, we understand the critical elements that make corporate conferences impactful and productive.",
      "Our versatile conference facilities include the magnificent 1,637 square meter Grand Ballroom capable of accommodating up to 2,300 attendees in theatre style, complemented by 9 additional meeting rooms that can be configured for breakout sessions, workshops, and executive meetings. Every space is equipped with cutting-edge audiovisual technology, high-speed internet connectivity, and professional support to ensure seamless presentations.",
      "From annual general meetings and shareholder conferences to multi-day corporate retreats, our dedicated events team works closely with your organization to deliver a conference experience that exceeds expectations. We handle every detail — from registration desk setup and name badge printing to coffee breaks, business lunches, and networking dinners — allowing you to focus on your conference content and delegates.",
      "As a TCEB-certified MICE venue with SHA Plus and Green Hotel certifications, Royal Phuket City Hotel offers the credibility and professional standards that leading corporations demand. Our central location in Phuket Town provides convenient access for domestic and international delegates, with nearby accommodations, dining, and cultural attractions for pre and post-conference activities.",
    ],
    features: [
      { title: "Grand Ballroom", description: "1,637 sqm flagship venue accommodating 2,300 theatre-style or 1,000 banquet guests" },
      { title: "Breakout Rooms", description: "9 versatile meeting rooms for workshops, seminars, and parallel sessions" },
      { title: "AV Technology", description: "HD projectors, LED walls, wireless presentation systems, and video conferencing" },
      { title: "High-Speed WiFi", description: "Dedicated bandwidth for conferences with hundreds of connected devices" },
      { title: "Registration Services", description: "Professional setup with badge printing, check-in systems, and welcome desks" },
      { title: "Catering Excellence", description: "Customizable menus with coffee breaks, business lunches, and gala dinners" },
    ],
    whyChooseUs: [
      "Southern Thailand's largest indoor conference venue",
      "TCEB-certified MICE venue with international standards",
      "27+ years of corporate event experience",
      "Dedicated conference coordinators and AV technicians",
      "Flexible room configurations for 10 to 2,300 attendees",
      "On-site accommodation with 251 rooms",
      "Over 350 parking spaces for delegates",
      "Strategic location near Phuket International Airport",
    ],
    idealFor: [
      "Annual General Meetings (AGM)",
      "Shareholder conferences",
      "Industry conferences and summits",
      "Corporate retreats and team gatherings",
      "Multi-day business conferences",
      "Regional business forums",
    ],
    venueOptions: [
      { name: "Grand Ballroom", capacity: "Up to 2,300 guests", bestFor: "Large conferences and plenary sessions" },
      { name: "Ballroom 1 & 2", capacity: "Up to 1,000 guests", bestFor: "Medium conferences" },
      { name: "Raya Room", capacity: "Up to 180 guests", bestFor: "Breakout sessions" },
      { name: "Si-Rea Room", capacity: "Up to 10 guests", bestFor: "Executive meetings" },
    ],
    gallery: [
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-1.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-2.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-3.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-4.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-5.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-6.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-7.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-8.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-9.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-10.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-11.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-12.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-13.jpg",
    ],
  },

  "seminar-workshop": {
    slug: "seminar-workshop",
    title: "Seminar & Workshop",
    subtitle: "Interactive Learning Environments for Professional Development",
    label: "Knowledge Exchange",
    heroImage: "/images/HOTEL WEBSITE/EVT_SW_L03_hands_collaboration_closeup.jpg",
    metaDescription: "Organize professional seminars and workshops in Phuket at Royal Phuket City Hotel. Flexible classroom setups, presentation technology, and expert event support for training sessions up to 800 attendees.",
    seoKeywords: ["seminar venue Phuket", "workshop space Thailand", "training room Phuket", "professional development venue", "corporate training Phuket", "seminar room rental Phuket", "educational workshop venue"],
    description: [
      "Transform knowledge into action with seminars and workshops hosted at Royal Phuket City Hotel. Our purpose-built training facilities combine comfortable learning environments with cutting-edge presentation technology, creating the ideal setting for professional development, skill-building workshops, and educational seminars.",
      "Whether you're conducting a half-day leadership workshop or a multi-day certification program, our venues adapt to your teaching methodology. Choose from traditional classroom layouts for lectures and presentations, U-shaped configurations for interactive discussions, or cluster arrangements for group activities and hands-on workshops.",
      "Our experienced events team understands the unique requirements of educational programming. We provide seamless AV support for presentations, demonstrations, and video content, along with comfortable seating arrangements that keep participants engaged throughout the day. Breakout spaces adjacent to main training rooms facilitate small group exercises and networking opportunities.",
      "Fuel productive learning with our thoughtfully designed coffee breaks and lunch services. Our catering team provides energizing refreshments that maintain focus and encourage networking during breaks, while our business lunch menus offer nutritious options that won't leave participants drowsy for afternoon sessions.",
      "From corporate training programs and professional certification courses to academic seminars and industry workshops, Royal Phuket City Hotel delivers the professional environment and support services that educators and trainers need to deliver impactful learning experiences.",
    ],
    features: [
      { title: "Flexible Layouts", description: "Classroom, U-shape, cluster, and theatre configurations to match your methodology" },
      { title: "Presentation Tech", description: "LCD projectors, wireless presenters, whiteboards, and flipcharts" },
      { title: "Breakout Spaces", description: "Adjacent rooms for small group activities and exercises" },
      { title: "Participant Materials", description: "Notepads, pens, and printing services for handouts and worksheets" },
      { title: "Coffee Breaks", description: "Energizing refreshments with healthy snack options" },
      { title: "On-Site Support", description: "Technical assistance and room setup throughout your program" },
    ],
    whyChooseUs: [
      "Rooms configured specifically for learning environments",
      "Natural lighting options to maintain energy levels",
      "Comfortable seating for full-day sessions",
      "Quiet, distraction-free spaces",
      "Professional AV technicians on standby",
      "Catering designed for productive learning",
      "Accommodation packages for multi-day programs",
      "Central location accessible to participants",
    ],
    idealFor: [
      "Corporate training programs",
      "Professional certification courses",
      "Leadership development workshops",
      "Team-building seminars",
      "Industry skill-building sessions",
      "Academic and educational seminars",
    ],
    venueOptions: [
      { name: "Ballroom 1", capacity: "Up to 300 classroom", bestFor: "Large seminars" },
      { name: "Raya Room", capacity: "Up to 80 classroom", bestFor: "Medium workshops" },
      { name: "Hay-Nakha", capacity: "Up to 60 classroom", bestFor: "Training sessions" },
      { name: "Bon-Maithon", capacity: "Up to 60 classroom", bestFor: "Interactive workshops" },
    ],
    gallery: [
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-1.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-2.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-3.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-4.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-5.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-6.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-7.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-8.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-9.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-10.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-11.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-12.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-13.jpg",
    ],
  },

  "product-launch": {
    slug: "product-launch",
    title: "Product Launch",
    subtitle: "Make Your Brand Debut Unforgettable",
    label: "Brand Reveal",
    heroImage: "/images/HOTEL WEBSITE/F45_PL_L02_presenter_product_medium.jpg",
    metaDescription: "Launch your product in style at Royal Phuket City Hotel. Dramatic reveal venues, LED displays, professional staging, and complete event production for impactful brand launches in Phuket.",
    seoKeywords: ["product launch venue Phuket", "brand launch event Thailand", "product reveal space", "launch event venue Phuket", "corporate launch party", "new product event Phuket", "brand activation venue"],
    description: [
      "First impressions matter, and at Royal Phuket City Hotel, we specialize in creating product launch experiences that captivate audiences and generate lasting brand impact. Our versatile venues transform into stunning showcase spaces where your product takes center stage under professional lighting and dramatic presentation setups.",
      "From automotive reveals requiring drive-in capabilities to tech product demonstrations needing sophisticated AV integration, our experienced production team works with you to design the perfect launch environment. The Grand Ballroom offers a blank canvas of 1,637 square meters that can be completely customized with staging, LED walls, themed décor, and immersive brand experiences.",
      "We understand that successful product launches require meticulous attention to detail and seamless execution. Our events team coordinates every element — from media registration and press kit distribution to product display setups and VIP reception areas. Professional photographers and videographers can be arranged to capture every moment of your brand's big reveal.",
      "Complement your launch event with sophisticated catering that reflects your brand's personality. Whether you envision an elegant cocktail reception, a seated dinner celebrating your achievement, or a vibrant after-party, our culinary team creates memorable dining experiences that extend the impact of your launch.",
      "With high-speed internet for live streaming, social media walls for audience engagement, and technical support for complex multimedia presentations, Royal Phuket City Hotel provides everything you need to make your product launch a resounding success.",
    ],
    features: [
      { title: "LED Display Walls", description: "High-resolution screens for dramatic product reveals and video content" },
      { title: "Professional Staging", description: "Custom stage setups with professional lighting design" },
      { title: "Product Display Areas", description: "Flexible spaces for hands-on product experiences" },
      { title: "Media Facilities", description: "Press rooms, interview areas, and media registration" },
      { title: "Live Streaming", description: "High-speed connectivity for global audience reach" },
      { title: "Themed Décor", description: "Complete venue transformation to match brand identity" },
    ],
    whyChooseUs: [
      "1,637 sqm blank canvas venue for creative setups",
      "Drive-in access for automotive reveals",
      "Professional AV and lighting teams",
      "Complete event production support",
      "Media coordination and press management",
      "Social media integration capabilities",
      "Sophisticated catering for brand alignment",
      "Post-event networking and celebration spaces",
    ],
    idealFor: [
      "Automotive vehicle launches",
      "Technology product reveals",
      "Fashion and beauty brand launches",
      "Consumer product introductions",
      "B2B product presentations",
      "Brand anniversary celebrations",
    ],
    venueOptions: [
      { name: "Grand Ballroom", capacity: "Up to 2,000 cocktail", bestFor: "Major product reveals" },
      { name: "Ballroom 1 & 2", capacity: "Up to 1,200 cocktail", bestFor: "Medium launches" },
      { name: "Ballroom 1", capacity: "Up to 250 cocktail", bestFor: "Intimate brand events" },
      { name: "TWIST Rooftop", capacity: "Up to 100 guests", bestFor: "VIP press events" },
    ],
    gallery: [
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-1.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-2.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-3.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-4.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-5.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-6.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-7.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-8.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-9.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-10.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-11.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-12.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-13.jpg",
    ],
  },

  "gala-dinner-award": {
    slug: "gala-dinner-award",
    title: "Gala Dinner & Awards",
    subtitle: "Celebrate Excellence in Grand Style",
    label: "Celebration of Excellence",
    heroImage: "/images/HOTEL WEBSITE/F45_GA_L04_gala_table_medium.jpg",
    metaDescription: "Host prestigious gala dinners and award ceremonies in Phuket at Royal Phuket City Hotel. Elegant ballroom settings, gourmet dining, and professional event production for up to 1,000 banquet guests.",
    seoKeywords: ["gala dinner venue Phuket", "award ceremony Thailand", "corporate awards event", "black tie event venue Phuket", "annual dinner venue", "gala event Phuket", "awards night venue Thailand"],
    description: [
      "Celebrate achievements and milestones with a prestigious gala dinner at Royal Phuket City Hotel. Our Grand Ballroom transforms into an elegant venue worthy of your most distinguished occasions, featuring crystal chandeliers, sophisticated décor, and impeccable service that creates an atmosphere of celebration and recognition.",
      "Whether you're hosting annual corporate awards, industry recognition ceremonies, charity galas, or milestone celebrations, our experienced banquet team delivers flawless execution from arrival to finale. We understand the importance of timing, presentation, and atmosphere in creating memorable award ceremonies that honor recipients and inspire audiences.",
      "Our culinary team crafts exquisite multi-course menus that elevate the dining experience to match the prestige of your event. From elegant canapés during the reception through artfully plated courses and decadent desserts, every dish reflects our commitment to culinary excellence. Dietary requirements and cultural preferences are accommodated with equal attention to presentation and taste.",
      "Professional staging and AV support ensure award presentations are impactful and seamlessly executed. Our team manages all technical requirements — from nominee video montages and announcement graphics to live camera feeds displayed on LED screens — while our events coordinators handle run-of-show timing, ensuring smooth transitions throughout the evening.",
      "Complete your gala with sophisticated entertainment options, from live bands and string quartets during dinner to DJ performances for the after-party. Royal Phuket City Hotel creates the complete gala experience that celebrates excellence in unforgettable style.",
    ],
    features: [
      { title: "Elegant Ballroom", description: "Crystal chandeliers, sophisticated décor, and premium table settings" },
      { title: "Gourmet Dining", description: "Multi-course menus crafted by executive chefs" },
      { title: "Stage & AV", description: "Professional staging, LED walls, and presentation systems" },
      { title: "Red Carpet Setup", description: "Arrival experience with photo opportunities" },
      { title: "Entertainment", description: "Live bands, DJs, and performance coordination" },
      { title: "Event Coordination", description: "Run-of-show management and seamless execution" },
    ],
    whyChooseUs: [
      "Prestigious ballroom setting with elegant ambiance",
      "Award-winning culinary team",
      "Professional stage and award presentation setup",
      "Complete AV production capabilities",
      "Experienced gala event coordinators",
      "Premium beverage and bar services",
      "VIP reception and networking areas",
      "Post-event after-party spaces",
    ],
    idealFor: [
      "Annual corporate awards ceremonies",
      "Industry recognition events",
      "Charity and fundraising galas",
      "Company anniversary celebrations",
      "Employee appreciation dinners",
      "Black-tie corporate events",
    ],
    venueOptions: [
      { name: "Grand Ballroom", capacity: "Up to 1,000 banquet", bestFor: "Major gala events" },
      { name: "Ballroom 1 & 2", capacity: "Up to 450 banquet", bestFor: "Medium awards ceremonies" },
      { name: "Ballroom 1", capacity: "Up to 250 banquet", bestFor: "Intimate gala dinners" },
      { name: "Ballroom 2", capacity: "Up to 200 banquet", bestFor: "Department celebrations" },
    ],
    gallery: [
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-1.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-2.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-3.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-4.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-5.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-6.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-7.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-8.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-9.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-10.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-11.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-12.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-13.jpg",
    ],
  },

  "stand-up-comedy": {
    slug: "stand-up-comedy",
    title: "Stand-Up Comedy Show",
    subtitle: "Where Laughter Takes Center Stage",
    label: "Entertainment",
    heroImage: "/images/HOTEL WEBSITE/EVT_SU_L02_comedian_punchline_medium.jpg",
    metaDescription: "Host stand-up comedy shows and entertainment events in Phuket at Royal Phuket City Hotel. Theatre-style seating for 2,300, professional stage and sound systems, and full production support.",
    seoKeywords: ["stand-up comedy venue Phuket", "comedy show Thailand", "entertainment venue Phuket", "live performance space", "comedy night venue", "stand-up show Phuket", "live entertainment Phuket"],
    description: [
      "Bring the magic of live comedy to Phuket at Royal Phuket City Hotel, where our professional entertainment facilities create the perfect atmosphere for stand-up performances that leave audiences laughing. Our venues combine excellent acoustics, comfortable seating, and professional production support to deliver memorable comedy experiences.",
      "The Grand Ballroom offers theatre-style seating for up to 2,300 guests, making it ideal for touring comedy acts and major entertainment events. The elevated stage, professional lighting, and concert-quality sound system ensure performers can connect with audiences in the back row as easily as those up front.",
      "For more intimate comedy club atmospheres, our smaller venues can be configured with cabaret-style seating that creates the close audience-performer connection essential for stand-up comedy. Tables allow for food and beverage service during performances, replicating the classic comedy club experience.",
      "Our experienced production team handles all technical requirements — from stage lighting and spotlight operation to microphone setup and sound mixing. We work with performers and promoters to ensure sound checks, run-throughs, and show execution meet professional touring standards.",
      "Whether you're organizing a one-night comedy special, a comedy festival weekend, or a corporate entertainment evening, Royal Phuket City Hotel provides the venue, production support, and hospitality services that make comedy events successful. From ticket sales support to VIP meet-and-greet arrangements, we handle every detail so audiences can focus on enjoying the show.",
    ],
    features: [
      { title: "Professional Stage", description: "Elevated stage with professional lighting and backdrops" },
      { title: "Concert Sound", description: "High-quality PA system with wireless microphones" },
      { title: "Flexible Seating", description: "Theatre, cabaret, or comedy club configurations" },
      { title: "Spotlight Systems", description: "Follow spots and programmable stage lighting" },
      { title: "Green Room", description: "Comfortable performer preparation spaces" },
      { title: "F&B Service", description: "Food and beverage service during performances" },
    ],
    whyChooseUs: [
      "Theatre seating for up to 2,300 audience members",
      "Professional stage and lighting systems",
      "Concert-quality sound equipment",
      "Experienced production technicians",
      "Intimate cabaret setup options",
      "Full bar and food service capabilities",
      "VIP and meet-and-greet facilities",
      "Convenient parking for large audiences",
    ],
    idealFor: [
      "Stand-up comedy tours and specials",
      "Comedy festival events",
      "Corporate entertainment nights",
      "Charity comedy fundraisers",
      "Comedy club-style performances",
      "Open mic and emerging talent nights",
    ],
    venueOptions: [
      { name: "Grand Ballroom", capacity: "Up to 2,300 theatre", bestFor: "Major comedy tours" },
      { name: "Ballroom 1", capacity: "Up to 500 theatre", bestFor: "Mid-size shows" },
      { name: "Ballroom 2", capacity: "Up to 300 theatre", bestFor: "Intimate comedy nights" },
      { name: "Raya Room", capacity: "Up to 180 theatre", bestFor: "Comedy club setup" },
    ],
    gallery: [
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-1.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-2.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-3.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-4.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-5.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-6.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-7.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-8.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-9.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-10.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-11.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-12.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-13.jpg",
    ],
  },

  "religious-ceremony": {
    slug: "religious-ceremony",
    title: "Religious & Spiritual Ceremony",
    subtitle: "Sacred Spaces for Meaningful Gatherings",
    label: "Spiritual Events",
    heroImage: "/images/HOTEL WEBSITE/F45_CC_P01_speaker_portrait.jpg",
    metaDescription: "Host religious ceremonies and spiritual gatherings in Phuket at Royal Phuket City Hotel. Respectful facilities for Buddhist ceremonies, prayer meetings, and faith-based events.",
    seoKeywords: ["religious ceremony venue Phuket", "spiritual event Thailand", "Buddhist ceremony venue", "prayer meeting hall", "faith event Phuket", "religious gathering venue", "ceremony hall Thailand"],
    description: [
      "Royal Phuket City Hotel respectfully welcomes religious and spiritual gatherings, providing dignified venues for ceremonies, prayer meetings, and faith-based community events. Our experienced team understands the reverence these occasions require and ensures appropriate arrangements that honor various religious traditions.",
      "Whether you're organizing Buddhist merit-making ceremonies, Christian worship services, Muslim prayer gatherings, or interfaith community events, our venues can be configured to support your spiritual practices. We provide respectful spaces free from distractions, with appropriate seating arrangements and technical support for your ceremony requirements.",
      "For Buddhist ceremonies, we facilitate arrangements including altar setups, monk seating protocols, and traditional décor. Our team is experienced in coordinating with temples and religious leaders to ensure ceremonies proceed according to proper customs and traditions.",
      "Our catering team accommodates religious dietary requirements with halal options, vegetarian Buddhist cuisine, and other faith-specific menus. We ensure that food service respects the religious observances of your community.",
      "With venues ranging from intimate prayer rooms to large halls accommodating hundreds of worshippers, Royal Phuket City Hotel provides appropriate spaces for religious communities to gather, celebrate, and worship together.",
    ],
    features: [
      { title: "Respectful Spaces", description: "Dignified venues configured for religious observance" },
      { title: "Altar Arrangements", description: "Appropriate setups for various religious traditions" },
      { title: "Religious Catering", description: "Halal, vegetarian, and faith-specific menu options" },
      { title: "AV Support", description: "Sound systems and displays for services and presentations" },
      { title: "Privacy", description: "Separate spaces for gender-specific requirements" },
      { title: "Coordination", description: "Liaison with religious leaders and communities" },
    ],
    whyChooseUs: [
      "Respectful and experienced event team",
      "Flexible venue configurations",
      "Religious dietary accommodations",
      "Appropriate décor and setup support",
      "Privacy and separate space options",
      "AV systems for services and ceremonies",
      "Central community-accessible location",
      "Ample parking for congregations",
    ],
    idealFor: [
      "Buddhist merit-making ceremonies",
      "Prayer meetings and worship services",
      "Religious community gatherings",
      "Faith-based conferences",
      "Interfaith dialogue events",
      "Religious holiday celebrations",
    ],
    venueOptions: [
      { name: "Grand Ballroom", capacity: "Up to 2,000 worshippers", bestFor: "Large ceremonies" },
      { name: "Ballroom 1", capacity: "Up to 500 worshippers", bestFor: "Community gatherings" },
      { name: "Raya Room", capacity: "Up to 180 worshippers", bestFor: "Prayer meetings" },
      { name: "Smaller Rooms", capacity: "20-80 worshippers", bestFor: "Intimate ceremonies" },
    ],
    gallery: [
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-1.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-2.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-3.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-4.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-5.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-6.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-7.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-8.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-9.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-10.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-11.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-12.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-13.jpg",
    ],
  },

  "exhibition-trade-show": {
    slug: "exhibition-trade-show",
    title: "Exhibition & Trade Show",
    subtitle: "Showcase Your Business to the World",
    label: "Business Showcase",
    heroImage: "/images/HOTEL WEBSITE/EVT_EX_L01_tradeshow_floor_wide.jpg",
    metaDescription: "Host exhibitions and trade shows in Phuket at Royal Phuket City Hotel. 1,637 sqm exhibition space, drive-in access for large displays, and complete trade show infrastructure.",
    seoKeywords: ["exhibition venue Phuket", "trade show Thailand", "expo venue Phuket", "business exhibition", "trade fair venue", "exhibition hall Phuket", "trade show space Thailand"],
    description: [
      "Transform business connections into opportunities at Royal Phuket City Hotel's premier exhibition facilities. Our expansive venues provide the flexible space and infrastructure needed to host successful trade shows, exhibitions, and business showcases that bring together vendors, buyers, and industry professionals.",
      "The 1,637 square meter Grand Ballroom offers a blank canvas for exhibition layouts, with high ceilings that accommodate large displays, oversized signage, and creative booth constructions. Floor-loading access through large service entrances enables easy movement of heavy equipment, vehicles, and oversized display materials.",
      "Our experienced events team works with exhibition organizers to ensure seamless logistics — from booth allocation and utility connections to exhibitor services and visitor registration. We provide exhibition essentials including tables, chairs, partitions, and electrical connections, with additional equipment available through our network of trusted vendors.",
      "Multiple entrance points allow for controlled visitor flow and efficient registration processes. Adjacent meeting rooms serve as VIP suites, press rooms, or private meeting spaces for exhibitor-client negotiations. Food and beverage services keep exhibitors and visitors energized throughout multi-day events.",
      "With on-site accommodation, ample parking, and a central location in Phuket Town, Royal Phuket City Hotel provides exhibitors and visitors with a convenient, professional environment for business networking and commerce.",
    ],
    features: [
      { title: "Exhibition Space", description: "1,637 sqm flexible hall with 6-meter ceiling height" },
      { title: "Loading Access", description: "Drive-in capability for heavy equipment and displays" },
      { title: "Booth Infrastructure", description: "Partitions, tables, chairs, and electrical connections" },
      { title: "Registration Systems", description: "Visitor management and badge printing services" },
      { title: "Meeting Rooms", description: "Adjacent spaces for VIP meetings and negotiations" },
      { title: "F&B Services", description: "Exhibitor catering and visitor refreshment areas" },
    ],
    whyChooseUs: [
      "Southern Thailand's largest indoor exhibition space",
      "High ceilings for large displays and signage",
      "Drive-in access for vehicle exhibitions",
      "Flexible booth and layout configurations",
      "Professional exhibition infrastructure",
      "Adjacent meeting and networking rooms",
      "On-site parking for 350+ vehicles",
      "Accommodation for exhibitors and visitors",
    ],
    idealFor: [
      "Industry trade shows",
      "Product exhibitions",
      "Job and career fairs",
      "Consumer expos",
      "Automotive shows",
      "Technology showcases",
    ],
    venueOptions: [
      { name: "Grand Ballroom", capacity: "80+ standard booths", bestFor: "Major trade shows" },
      { name: "Ballroom 1 & 2", capacity: "40+ standard booths", bestFor: "Medium exhibitions" },
      { name: "Ballroom 1", capacity: "20+ standard booths", bestFor: "Boutique showcases" },
      { name: "Outdoor Areas", capacity: "Variable", bestFor: "Automotive displays" },
    ],
    gallery: [
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-1.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-2.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-3.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-4.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-5.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-6.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-7.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-8.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-9.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-10.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-11.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-12.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-13.jpg",
    ],
  },

  "concert-live-performance": {
    slug: "concert-live-performance",
    title: "Concert & Live Performance",
    subtitle: "Where Music Comes Alive",
    label: "Live Entertainment",
    heroImage: "/images/HOTEL WEBSITE/F45_CN_L02_performer_medium.jpg",
    metaDescription: "Host concerts and live performances in Phuket at Royal Phuket City Hotel. Professional stage, concert sound systems, and capacity for 2,300 guests for memorable musical events.",
    seoKeywords: ["concert venue Phuket", "live performance Thailand", "music venue Phuket", "entertainment hall", "live music Phuket", "concert hall Thailand", "performance venue Phuket"],
    description: [
      "Bring world-class entertainment to Phuket at Royal Phuket City Hotel, where our concert-ready facilities deliver unforgettable live performance experiences. From intimate acoustic sets to full-scale concert productions, our venues provide the technical infrastructure and audience capacity that artists and promoters demand.",
      "The Grand Ballroom accommodates up to 2,300 guests in theatre configuration, with flexible layouts allowing for general admission standing, reserved seating, or mixed arrangements. The 6-meter ceiling height provides clearance for professional lighting rigs, sound systems, and stage productions, while the column-free space ensures unobstructed sightlines throughout the venue.",
      "Our technical capabilities meet touring production standards with high-capacity electrical supply, professional rigging points, and acoustic properties suitable for amplified performances. Whether you're bringing in a full production or utilizing our in-house systems, our experienced crew supports seamless technical execution.",
      "Multiple access points facilitate efficient audience flow, while backstage areas include artist green rooms, production offices, and secure load-in routes. Our team coordinates with production managers, security companies, and vendors to ensure all elements come together for a successful show.",
      "Beyond the main venue, adjacent spaces serve as VIP reception areas, merchandise locations, and after-party venues. Royal Phuket City Hotel provides complete concert solutions from load-in to load-out, helping artists and promoters deliver performances that audiences remember long after the final encore.",
    ],
    features: [
      { title: "Concert Stage", description: "Professional staging with rigging points and load capacity" },
      { title: "Sound Systems", description: "Concert-grade PA systems and monitor arrangements" },
      { title: "Lighting Rigs", description: "High-capacity power and professional lighting infrastructure" },
      { title: "Backstage Facilities", description: "Green rooms, production offices, and secure areas" },
      { title: "Audience Management", description: "Multiple entry points and crowd management support" },
      { title: "VIP Areas", description: "Premium viewing positions and exclusive hospitality" },
    ],
    whyChooseUs: [
      "Capacity for 2,300 concert-goers",
      "6-meter ceiling height for production rigs",
      "Professional rigging and power supply",
      "Column-free venue with clear sightlines",
      "Experienced production crew support",
      "Secure load-in and backstage access",
      "VIP and hospitality capabilities",
      "After-party and networking spaces",
    ],
    idealFor: [
      "Concert tours and one-night performances",
      "Music festivals and showcases",
      "Corporate entertainment events",
      "Charity concert fundraisers",
      "CD/album launch events",
      "Fan meeting and fan concert events",
    ],
    venueOptions: [
      { name: "Grand Ballroom", capacity: "Up to 2,300 guests", bestFor: "Major concerts" },
      { name: "Ballroom 1 & 2", capacity: "Up to 1,000 guests", bestFor: "Mid-size performances" },
      { name: "Ballroom 1", capacity: "Up to 500 guests", bestFor: "Intimate shows" },
      { name: "TWIST Rooftop", capacity: "Up to 100 guests", bestFor: "Acoustic sessions" },
    ],
    gallery: [
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-1.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-2.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-3.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-4.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-5.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-6.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-7.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-8.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-9.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-10.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-11.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-12.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-13.jpg",
    ],
  },

  "company-party-celebration": {
    slug: "company-party-celebration",
    title: "Company Party & Celebration",
    subtitle: "Celebrate Your Team's Success",
    label: "Team Celebration",
    heroImage: "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-1.jpg",
    metaDescription: "Host memorable company parties and celebrations in Phuket at Royal Phuket City Hotel. Year-end parties, staff appreciation events, and themed celebrations for up to 1,000 guests.",
    seoKeywords: ["company party venue Phuket", "corporate celebration Thailand", "year-end party venue", "staff party Phuket", "company celebration", "corporate party Thailand", "team celebration venue"],
    description: [
      "Celebrate your team's achievements and build company culture with unforgettable corporate celebrations at Royal Phuket City Hotel. Whether you're planning a year-end party, staff appreciation event, company anniversary, or departmental celebration, our venues and experienced events team create memorable experiences that motivate and inspire.",
      "Our versatile ballrooms transform to match any party theme or company culture — from elegant formal dinners recognizing top performers to casual cocktail parties celebrating project completions. The Grand Ballroom accommodates celebrations for up to 1,000 guests in banquet style, while our smaller venues provide intimate settings for department gatherings.",
      "Every celebration deserves great food, and our culinary team delivers party-perfect menus ranging from international buffets and live cooking stations to formal plated dinners. Our bartenders craft signature cocktails, and we coordinate entertainment from DJs and live bands to team-building activities and interactive games.",
      "Let us handle the details that make company parties special — themed décor, photo booths, lucky draws, and award presentations. Our events coordinators work with your HR and admin teams to ensure smooth execution while you focus on celebrating with your colleagues.",
      "With on-site accommodation for overnight guests and ample parking for all attendees, Royal Phuket City Hotel makes company celebrations convenient and stress-free. Create lasting memories and strengthen team bonds with parties that show your appreciation for your most valuable asset — your people.",
    ],
    features: [
      { title: "Themed Décor", description: "Custom decorations and setups matching company culture" },
      { title: "Entertainment", description: "DJs, live bands, and interactive activities" },
      { title: "Party Catering", description: "Buffets, cocktail menus, and live cooking stations" },
      { title: "Photo Stations", description: "Photo booths and backdrop setups for memories" },
      { title: "Award Setup", description: "Stage and presentation arrangements for recognition" },
      { title: "Lucky Draws", description: "Prize coordination and announcement systems" },
    ],
    whyChooseUs: [
      "Venues accommodating 20 to 1,000 guests",
      "Flexible party format options",
      "Creative theming and décor services",
      "Complete entertainment coordination",
      "Experienced party planners",
      "Premium bar and beverage service",
      "On-site accommodation for overnight events",
      "Convenient parking for all guests",
    ],
    idealFor: [
      "Year-end and new year parties",
      "Staff appreciation events",
      "Company anniversary celebrations",
      "Department team gatherings",
      "Project completion parties",
      "Retirement and farewell celebrations",
    ],
    venueOptions: [
      { name: "Grand Ballroom", capacity: "Up to 1,000 banquet", bestFor: "Company-wide celebrations" },
      { name: "Ballroom 1 & 2", capacity: "Up to 450 banquet", bestFor: "Large department parties" },
      { name: "Ballroom 1", capacity: "Up to 250 banquet", bestFor: "Medium team events" },
      { name: "Raya Room", capacity: "Up to 90 banquet", bestFor: "Intimate gatherings" },
    ],
    gallery: [
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-1.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-2.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-3.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-4.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-5.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-6.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-7.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-8.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-9.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-10.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-11.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-12.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-13.jpg",
    ],
  },

  "government-meeting": {
    slug: "government-meeting",
    title: "Government & Official Meeting",
    subtitle: "Professional Venues for Public Sector Excellence",
    label: "Official Events",
    heroImage: "/images/HOTEL WEBSITE/EVT_SW_P01_participant_focused_portrait.jpg",
    metaDescription: "Host government meetings and official events in Phuket at Royal Phuket City Hotel. Secure facilities, professional protocols, and capacity for large-scale public sector gatherings.",
    seoKeywords: ["government meeting venue Phuket", "official event Thailand", "public sector venue", "government conference Phuket", "official meeting hall", "GCC venue Thailand", "government seminar Phuket"],
    description: [
      "Royal Phuket City Hotel provides distinguished facilities for government meetings, official conferences, and public sector events. With extensive experience hosting provincial, national, and international government gatherings, we understand the protocols, security requirements, and professional standards that official events demand.",
      "Our TCEB-certified venues meet the standards required for government conventions and conferences, with flexible configurations supporting everything from cabinet-level boardroom meetings to large-scale public forums. The Grand Ballroom accommodates over 2,000 attendees for major government assemblies, while secure meeting rooms provide confidential spaces for sensitive discussions.",
      "Security and protocol are paramount for official events. Our team coordinates with government security personnel, provides controlled access points, and ensures proper arrangements for VIP arrivals, media management, and official proceedings. We maintain the discretion and professionalism that government clients expect.",
      "Our experienced events team is familiar with official event requirements — from proper staging and flag protocols to simultaneous interpretation systems and official recording. We provide the technical infrastructure for professional presentations, video conferencing with remote participants, and broadcast-quality documentation of proceedings.",
      "Convenient to government offices in Phuket Town with ample parking and accommodation for delegates, Royal Phuket City Hotel offers a professional, accessible venue for government meetings that serve the public interest.",
    ],
    features: [
      { title: "Secure Facilities", description: "Controlled access and security coordination capabilities" },
      { title: "VIP Protocols", description: "Proper arrangements for official arrivals and proceedings" },
      { title: "Interpretation", description: "Simultaneous interpretation systems and translator booths" },
      { title: "Recording", description: "Professional documentation and broadcast capabilities" },
      { title: "Media Management", description: "Press rooms and media coordination areas" },
      { title: "Certification", description: "TCEB-certified MICE venue meeting official standards" },
    ],
    whyChooseUs: [
      "TCEB-certified venue meeting government standards",
      "Experience with official protocols and procedures",
      "Secure meeting facilities",
      "VIP and dignitary handling capabilities",
      "Professional interpretation systems",
      "Media and press coordination",
      "Central location near government offices",
      "Ample parking and accommodation",
    ],
    idealFor: [
      "Government conferences and assemblies",
      "Official ministry meetings",
      "Public hearings and forums",
      "Inter-agency coordination meetings",
      "International official delegations",
      "Policy seminars and workshops",
    ],
    venueOptions: [
      { name: "Grand Ballroom", capacity: "Up to 2,300 theatre", bestFor: "Major government assemblies" },
      { name: "Ballroom 1 & 2", capacity: "Up to 1,000 theatre", bestFor: "Provincial conferences" },
      { name: "Ballroom 1", capacity: "Up to 500 theatre", bestFor: "Department meetings" },
      { name: "Si-Rea Room", capacity: "Up to 10 boardroom", bestFor: "Executive briefings" },
    ],
    gallery: [
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-1.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-2.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-3.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-4.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-5.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-6.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-7.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-8.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-9.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-10.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-11.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-12.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-13.jpg",
    ],
  },

  "talk-show-panel": {
    slug: "talk-show-panel",
    title: "Talk Show & Panel Discussion",
    subtitle: "Where Ideas Meet Audience",
    label: "Thought Leadership",
    heroImage: "/images/HOTEL WEBSITE/MTG_MW_10_emcee_energy_medium.jpg",
    metaDescription: "Host professional talk shows and panel discussions in Phuket at Royal Phuket City Hotel. Broadcast-ready facilities, panel staging, and live streaming capabilities for thought leadership events.",
    seoKeywords: ["talk show venue Phuket", "panel discussion Thailand", "forum venue Phuket", "thought leadership event", "speaker panel venue", "debate venue Phuket", "discussion forum Thailand"],
    description: [
      "Elevate discourse and share ideas at Royal Phuket City Hotel, where our professional facilities create the ideal setting for talk shows, panel discussions, and thought leadership forums. Whether you're hosting industry experts, political debates, or celebrity interviews, our venues deliver the broadcast-quality environment these events demand.",
      "Our experienced AV team understands the unique requirements of panel-format events. We provide comfortable raised panel seating with individual microphones, proper lighting for speakers and audience, large display screens for visual content, and camera positions for recording or live streaming. Every technical element is designed to facilitate engaging conversations that connect with both live and remote audiences.",
      "The flexibility of our venues allows for various talk show formats — from intimate fireside chats with a single guest to large panel discussions with multiple speakers and interactive audience participation. Our team configures seating, staging, and technology to match your specific program format and audience size.",
      "For events requiring broadcast or streaming, we provide high-speed internet connectivity, multi-camera setup coordination, and collaboration with production crews to ensure professional-quality content capture. Our facilities have hosted live television broadcasts, podcast recordings, and globally streamed corporate communications.",
      "From green rooms where speakers can prepare to reception areas for post-event networking, Royal Phuket City Hotel provides complete support for talk shows and panel discussions that inform, engage, and inspire audiences.",
    ],
    features: [
      { title: "Panel Staging", description: "Raised seating with individual microphones and monitors" },
      { title: "Audience Interaction", description: "Roving microphones and Q&A setup systems" },
      { title: "Broadcast Ready", description: "Multi-camera positions and professional lighting" },
      { title: "Live Streaming", description: "High-speed connectivity for global audience reach" },
      { title: "Display Systems", description: "LED walls and screens for presentations and graphics" },
      { title: "Green Rooms", description: "Comfortable speaker preparation areas" },
    ],
    whyChooseUs: [
      "Broadcast-quality lighting and sound",
      "Flexible panel configurations",
      "Professional AV technical support",
      "Live streaming and recording capabilities",
      "Comfortable audience seating",
      "Speaker preparation facilities",
      "Interactive audience technology",
      "Post-event networking spaces",
    ],
    idealFor: [
      "Industry expert panel discussions",
      "Political forums and debates",
      "Corporate leadership talks",
      "Media and press events",
      "Podcast and broadcast recordings",
      "Academic and research forums",
    ],
    venueOptions: [
      { name: "Grand Ballroom", capacity: "Up to 2,300 audience", bestFor: "Major public forums" },
      { name: "Ballroom 1", capacity: "Up to 500 audience", bestFor: "Industry panels" },
      { name: "Raya Room", capacity: "Up to 180 audience", bestFor: "Intimate discussions" },
      { name: "Hay-Nakha", capacity: "Up to 100 audience", bestFor: "Expert talks" },
    ],
    gallery: [
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-1.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-2.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-3.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-4.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-5.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-6.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-7.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-8.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-9.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-10.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-11.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-12.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-13.jpg",
    ],
  },

  "graduation-ceremony": {
    slug: "graduation-ceremony",
    title: "Graduation Ceremony",
    subtitle: "Celebrating Academic Achievement",
    label: "Academic Milestone",
    heroImage: "/images/HOTEL WEBSITE/EVT_GR_L03_diploma_hands_closeup.jpg",
    metaDescription: "Host graduation ceremonies in Phuket at Royal Phuket City Hotel. Professional staging, comfortable seating for 2,300 guests, and complete ceremony support for academic institutions.",
    seoKeywords: ["graduation ceremony venue Phuket", "commencement hall Thailand", "university graduation venue", "school graduation Phuket", "academic ceremony hall", "graduation event venue", "convocation hall Thailand"],
    description: [
      "Mark academic achievement with the dignity it deserves at Royal Phuket City Hotel, where our professional facilities provide the perfect setting for graduation ceremonies that students and families will remember forever. Our Grand Ballroom accommodates large graduating classes with comfortable seating for thousands of proud guests.",
      "We understand that graduation ceremonies require precise choreography and professional presentation. Our experienced team coordinates every element — from processional staging and diploma presentation setups to photography positions and family seating arrangements. The result is a smooth, dignified ceremony that honors graduates appropriately.",
      "Our technical capabilities support impressive ceremony presentations with high-quality sound systems for speeches and music, display screens for graduate names and photos, and professional lighting that creates the ceremonial atmosphere this milestone deserves. We work with schools and universities to execute their specific ceremony traditions and protocols.",
      "Beyond the main ceremony, we provide spaces for pre-ceremony staging, post-ceremony receptions, and family photo opportunities. Our catering team offers celebration packages from light refreshments to formal graduation dinners, allowing families to continue celebrating after the ceremony.",
      "With parking for hundreds of vehicles and a central location accessible to families across Phuket, Royal Phuket City Hotel makes graduation day convenient and memorable for graduates, families, and institutions alike.",
    ],
    features: [
      { title: "Ceremony Staging", description: "Professional setup for processionals and presentations" },
      { title: "Large Capacity", description: "Seating for 2,300 guests in theatre configuration" },
      { title: "AV Systems", description: "Sound, displays, and lighting for ceremonial atmosphere" },
      { title: "Photo Areas", description: "Backdrop setups for graduate and family photos" },
      { title: "Reception Spaces", description: "Adjacent areas for post-ceremony celebrations" },
      { title: "Catering", description: "Refreshments and formal dinner options" },
    ],
    whyChooseUs: [
      "Capacity for large graduating classes and families",
      "Professional ceremony staging and coordination",
      "Experienced with academic institution protocols",
      "High-quality AV for impactful presentations",
      "Comfortable seating for extended ceremonies",
      "Reception and celebration spaces",
      "Ample parking for families",
      "Accessible central location",
    ],
    idealFor: [
      "University graduation ceremonies",
      "College commencement events",
      "High school graduations",
      "Professional certification ceremonies",
      "Academic award ceremonies",
      "Alumni reunion events",
    ],
    venueOptions: [
      { name: "Grand Ballroom", capacity: "Up to 2,300 guests", bestFor: "Large graduations" },
      { name: "Ballroom 1 & 2", capacity: "Up to 1,000 guests", bestFor: "Medium ceremonies" },
      { name: "Ballroom 1", capacity: "Up to 500 guests", bestFor: "Smaller institutions" },
      { name: "Raya Room", capacity: "Up to 180 guests", bestFor: "Intimate ceremonies" },
    ],
    gallery: [
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-1.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-2.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-3.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-4.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-5.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-6.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-7.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-8.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-9.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-10.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-11.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-12.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-13.jpg",
    ],
  },

  "team-building": {
    slug: "team-building",
    title: "Team Building Event",
    subtitle: "Strengthen Bonds, Build Better Teams",
    label: "Team Development",
    heroImage: "/images/HOTEL WEBSITE/EVT_SW_L01_workshop_room_wide.jpg",
    metaDescription: "Organize team building events in Phuket at Royal Phuket City Hotel. Indoor and outdoor activities, facilitated programs, and complete logistics for corporate team development.",
    seoKeywords: ["team building venue Phuket", "corporate team event Thailand", "team building activities Phuket", "corporate outing venue", "team development event", "company team building", "group activities Phuket"],
    description: [
      "Build stronger, more cohesive teams at Royal Phuket City Hotel, where our venues and location provide the perfect foundation for team building events that energize, engage, and unite. Whether you're planning structured development programs or fun group activities, we create experiences that strengthen workplace relationships and boost team performance.",
      "Our indoor venues accommodate team building activities from small group workshops to company-wide events. The flexible Grand Ballroom transforms into activity zones for large-scale competitions, while our meeting rooms provide intimate spaces for team exercises, problem-solving challenges, and facilitated discussions.",
      "Our location in Phuket offers unique opportunities for outdoor team building that combines professional development with the island's natural beauty. We coordinate with trusted activity providers for beach challenges, water sports competitions, cultural experiences, and adventure activities that take teams beyond the conference room.",
      "For structured development programs, we support professional facilitators with appropriate room setups, AV equipment, and materials. Our events team handles logistics so facilitators can focus on their program content and participant engagement.",
      "Complete team building experiences include quality dining that brings teams together — from casual BBQ gatherings to formal team dinners. With on-site accommodation, teams can extend their bonding with overnight programs that maximize interaction and relationship building.",
    ],
    features: [
      { title: "Activity Spaces", description: "Flexible indoor venues for games and exercises" },
      { title: "Outdoor Options", description: "Coordination with beach and adventure activities" },
      { title: "Facilitator Support", description: "AV and materials for professional programs" },
      { title: "Team Catering", description: "Group dining from casual to formal styles" },
      { title: "Accommodation", description: "Overnight packages for extended programs" },
      { title: "Activity Partners", description: "Network of trusted activity providers" },
    ],
    whyChooseUs: [
      "Flexible venues for various activities",
      "Indoor and outdoor program options",
      "Professional facilitator support",
      "Team dining and social spaces",
      "On-site accommodation for overnight events",
      "Activity coordination and logistics",
      "Phuket location for unique experiences",
      "Experienced corporate event team",
    ],
    idealFor: [
      "Corporate team development programs",
      "Department bonding events",
      "New team integration activities",
      "Leadership development retreats",
      "Sales team motivation events",
      "Company-wide team challenges",
    ],
    venueOptions: [
      { name: "Grand Ballroom", capacity: "Up to 500 participants", bestFor: "Large team activities" },
      { name: "Ballroom 1", capacity: "Up to 200 participants", bestFor: "Department events" },
      { name: "Multiple Rooms", capacity: "Variable", bestFor: "Breakout activities" },
      { name: "Outdoor Areas", capacity: "Variable", bestFor: "Active challenges" },
    ],
    gallery: [
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-1.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-2.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-3.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-4.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-5.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-6.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-7.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-8.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-9.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-10.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-11.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-12.jpg",
      "/images/HOTEL WEBSITE/Banquet-Royal-Phuket-City-13.jpg",
    ],
  },
};

export const MICE_EVENT_TYPE_SLUGS = Object.keys(MICE_EVENT_TYPES);
